### ISSUE TITLE
Unique Filename

### ISSUE THREAD

**Issue by EduardSchwarzkopf** [nomisum/arma_photogrammetryCapture#1]
Not sure how it the screenshot function will behave when you take different images from the same object, but if I understand it correctly it will most likely override the ones already there.
So maybe add a timestamp with the systemTime function to the name, in the beginning, so they are definitely unique and sorted. https://community.bistudio.com/wiki/systemTime might

**Comment by nomisum** [comment]
Currently i am encoding index and object name, systemtime or position of object might be other unique id providers, yeah.

didnt actually test this yet as i have been in vacation.

thanks for the feedback.
